name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        
    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        cd build
        cpack
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: state-pattern-deb
        path: build/state-pattern-1.0.0-Linux.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: build/state-pattern-1.0.0-Linux.deb
        tag_name: v1.0.0
        name: Release v1.0.0
        body: State Pattern implementation with tests
