name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake .. -DBUILD_TESTS=ON
        cmake --build . --config Release
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        cd build
        cpack -G DEB
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: message-handler-package
        path: |
          build/*.deb
          build/Testing/**/*.xml
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/*.deb
          build/Testing/**/*.xml
